export interface User {
    id: string,
    name: string,
    adultsQuantity: number,
    kidsQuantity: number,
    adultsCounter: number,
    kidsCounter: number,
    qrCode: string,
    phone: string,
    keyPass: string,
    table: string,
    isActive: boolean,
    event: string,
    user: string,
}